#!/bin/bash
#
#       /etc/rc.d/init.d/
#
#
#
#
#

# Source function library.
. /etc/init.d/functions



start() {
        echo -n "Starting Framework service..."
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib64
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./notif
        pwd = 'pwd'
        export LD_LIBRARY_PATH=$pwd:$LD_LIBRARY_PATH
        
        ./framework &
        return
}

stop() {
        echo -n "Shutting down Framework service..."
	
        pkill -SIGTERM framework
        return
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    reload)
        pkill -SIGINT framework
        ;;
    *)
        echo "Usage:  {start|stop|restart[|probe]"
        exit 1
        ;;
esac
exit $?
